title: Jaxlicious
default_lang: en
author:
  name: author
  email: erik@bodigiti.com
taxonomies:
  - category
metadata:
  description: 'Beverly Hills Boxing Club is located in Los Angeles, California. For years we have had apparel for our members, now we offer our gear to you.'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
