<?php
namespace Grav\Theme;

use Grav\Common\Theme;

class Bodigiti extends Theme
{

  // Access plugin events in this class
  public static function styleSelect() {
    return array (
    'width__100' => 'Width 100',
    'margin-auto__right-left' => 'Margin Auto Right-Left',
    'contain-inner' => 'Contain Inner ',
    'contain-inner__xs' => 'Contain Inner XS',
    'contain-inner__sm' => 'Contain Inner SM',
    'contain-inner__sm-plus' => 'Contain Inner SM-Plus',
    'contain-inner__md' => 'Contain Inner MD',
    'contain-inner__lg' => 'Contain Inner LG',
    'contain-inner__xl' => 'Contain Inner XL',
    'contain-inner__2x' => 'Contain Inner 2X',
    'contain-outer' => 'Contain Outer ',
    'contain-outer__xs' => 'Contain Outer XS',
    'contain-outer__sm' => 'Contain Outer SM',
    'contain-outer__sm-plus' => 'Contain Outer SM-Plus',
    'contain-outer__md' => 'Contain Outer MD',
    'contain-outer__lg' => 'Contain Outer LG',
    'contain-outer__xl' => 'Contain Outer XL',
    'contain-outer__2x' => 'Contain Outer 2X',
    'show-xs' => 'Show XS ',
    'show-sm' => 'Show SM ',
    'show-sm-plus' => 'Show SM-Plus ',
    'show-md' => 'Show MD ',
    'show-lg' => 'Show LG ',
    'show-xl' => 'Show XL ',
    'show-2x' => 'Show 2X ',
    'hide-xs' => 'Hide XS ',
    'hide-sm' => 'Hide SM ',
    'hide-sm-plus' => 'Hide SM-Plus ',
    'hide-md' => 'Hide MD ',
    'hide-lg' => 'Hide LG ',
    'hide-xl' => 'Hide XL ',
    'hide-2x' => 'Hide 2X ',
    'background__1' => 'Background 1',
    'background__2' => 'Background 2',
    'background__3' => 'Background 3',
    'background__4' => 'Background 4',
    'background__4a' => 'Background 4 A',
    'background__5' => 'Background 5',
    'background__5a' => 'Background 5 A',
    'background__6' => 'Background 6',
    'background__6a' => 'Background 6 A',
    'background__7' => 'Background 7',
    'background__7a' => 'Background 7 A',
    'background__8' => 'Background 8',
    'background__8a' => 'Background 8 A',
    'background__9' => 'Background 9',
    'background__9a' => 'Background 9 A',
    'background__10' => 'Background 10',
    'background__10a' => 'Background 10 A',
    'background__gray1' => 'Background Gray1',
    'background__gray2' => 'Background Gray2',
    'background__gray3' => 'Background Gray3',
    'background__gray4' => 'Background Gray4',
    'background__gray5' => 'Background Gray5',
    'background__gray6' => 'Background Gray6',
    'background__gray7' => 'Background Gray7',
    'background__gray8' => 'Background Gray8',
    'background__gray9' => 'Background Gray9',
    'background__gray10' => 'Background Gray10',
    'background__gray11' => 'Background Gray11',
    'background__gray12' => 'Background Gray12',
    'image__xs' => 'Image XS',
    'image__sm' => 'Image SM',
    'image__md' => 'Image MD',
    'image__lg' => 'Image LG',
    'image__xl' => 'Image XL',
    'images-size__xs' => 'Images Size XS',
    'images-size__sm' => 'Images Size SM',
    'images-size__md' => 'Images Size MD',
    'images-size__lg' => 'Images Size LG',
    'image__right' => 'Image Right',
    'image__left' => 'Image Left',
    'image__center' => 'Image Center',
    'image__nowrap' => 'Image Nowrap',
    'images-padding__xxs' => 'Images Padding XXS',
    'images-padding__xs' => 'Images Padding XS',
    'images-padding__sm' => 'Images Padding SM',
    'images-padding__md' => 'Images Padding MD',
    'images-padding__lg' => 'Images Padding LG',
    'images-padding__xl' => 'Images Padding XL',
    'images-padding__xxl' => 'Images Padding XXL',
    'title__left' => 'Title Left',
    'title__center' => 'Title Center',
    'title__right' => 'Title Right',
    'text-align__center' => 'Text Align Center',
    'text-align__right' => 'Text Align Right',
    'text-align__left' => 'Text Align Left',
    'text-align__justify' => 'Text Align Justify',
    'text-color__white' => 'Text Color White',
    'text-color__brown' => 'Text Color Brown',
    'text-color__red' => 'Text Color Red',
    'paragraph__callout' => 'Paragraph Callout',
    'paragraphs-width__25' => 'Paragraphs Width 25',
    'paragraphs-width__33' => 'Paragraphs Width 33',
    'paragraphs-width__50' => 'Paragraphs Width 50',
    );
  } // End 'Style Select'

}
